# Generated by Django 5.0.3 on 2024-06-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0004_auto_20240611_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
